config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  resources :users, only: :show do
    member do
      get :following
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get '/pictureposts/search', to: 'pictureposts#search'
  resources :pictureposts do
    resources :comments, only: [:create]
  end
  post '/like/:picturepost_id', to: 'likes#like', as: 'like'
  delete '/like/:picturepost_id', to: 'likes#unlike', as: 'unlike'
  root 'home#top'
  get 'home/top'
end

app/models/picturepost.rb
class Picturepost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  mount_uploader :picture, PictureUploader
  validates :picture, presence: true
end

app/controllers/pictureposts_controller.rb
class PicturepostsController < ApplicationController
  before_action :authenticate_user!, only: %i[index show new create edit delete]
  before_action :correct_user, only: :destroy

  def index
    @pictureposts = Picturepost.all.order('created_at DESC')
  end

  def show
    @picturepost = Picturepost.find(params[:id])
    @comments = @picturepost.comments
    @comment = Comment.new
  end

  def new
    @picturepost = Picturepost.new
  end

  def create
    @picturepost = Picturepost.new(content: picturepost_params[:content], picture: picturepost_params[:picture], user_id: current_user.id)
    if @picturepost.save
      flash[:success] = '写真を投稿しました！'
      redirect_to picturepost_url(@picturepost)
    else
      render 'new'
    end
  end

  def destroy
    @picturepost.destroy
    flash[:danger] = '写真を削除しました！'
    redirect_to user_path(@picturepost.user)
  end

  def search
    @pictureposts = Picturepost.where('content LIKE ?', "%#{params[:search]}%")
  end

  private

  def picturepost_params
    params.require(:picturepost).permit(:content, :picture)
  end

  def correct_user
    @picturepost = current_user.pictureposts.find_by(id: params[:id])
    redirect_to root_url if @picturepost.nil?
  end
end

app/views/pictureposts/_gridpictures.html.erb
<div class="row grid">
  <% pictureposts.each do |picturepost| %>
    <div class="col-4 img-box">
      <%= link_to picturepost_path(picturepost) do%>
        <%= image_tag picturepost.picture.url if picturepost.picture? %>
      <% end %>
    </div>
  <% end %>     
</div>

app/views/pictureposts/_instacard.html.erb
<div class="card">
  <div class="card-header">        
    <div class="profile-info">
      <%= link_to user_path(picturepost.user) do%>
        <div class="name"><%= picturepost.user.username %></div>
      <% end %>
      <% if current_user?(picturepost.user) %>
        <%= link_to "削除", picturepost_path(picturepost), method: :delete, class: "btn btn-outline-secondary btn-sm", data: {confirm: '削除しますか？'} %>
      <% end%>    
      <% if !current_user?(picturepost.user) %>
        <%= render partial: 'partials/follow-btn', locals: {user: picturepost.user}%>
      <% end %>
    </div>
  </div>
  <div class="content">
    <%= link_to picturepost_path(picturepost) do %>
      <%= image_tag picturepost.picture.url if picturepost.picture? %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= render partial: 'likes/like', locals: {picturepost: picturepost} %>
    <div class="description">
      <p>
        <span class="username"><%= picturepost.user.username %></span><%= picturepost.content %>
      </p>
    </div>
    <hr />
    <%= render partial: 'comments/comment', locals: {picturepost: picturepost}%>
  </div>
</div>

app/views/pictureposts/index.html.erb
<% provide(:title, "NewPosts") %>

<div class="new_post_wrapper mt-5 pt-5 text-center"> 
  <div class="container-fluid">
    <h1>New Posts</h1>
    <%= render partial: 'pictureposts/gridpictures', locals: {pictureposts: @pictureposts}%>
  </div>
</div>

app/views/pictureposts/new.html.erb
<% provide(:title, "Post Picture") %>

<div class="new_post_page pt-5 mt-5 text-center">
  <h1>写真を投稿する</h1>
  <%= render partial: 'partials/error_messages', locals: {object: @picturepost}%>
  <%= form_for(@picturepost) do |f| %>
    <div class="field picture my-3 mt-5">
      <%= f.file_field :picture %>
    </div>
    <div class="field my-4">
      <%= f.text_area :content, placeholder: "コメントを入力してください..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-secondary btn-lg" %>
  <% end %>
</div>

app/views/pictureposts/search.html.erb
<% provide(:title, "Search") %>

<div class="new_post_wrapper mt-5 pt-5 text-center"> 
  <div class="container-fluid">
    <h1>検索結果</h1>
    <%= render partial: 'pictureposts/gridpictures', locals: {pictureposts: @pictureposts}%>
  </div>
</div>

app/views/pictureposts/show.html.erb
<% provide(:title, "Picture") %>

<div class="picturepost_show_wrapper pt-5 mt-3">
  <%= render 'partials/flash_messages' %>   
  <div class="instacard-container">
    <%= render partial: 'pictureposts/instacard', locals: {picturepost: @picturepost}%>    
  </div>
</div>