config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  resources :users, only: :show do
    member do
      get :following
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get '/pictureposts/search', to: 'pictureposts#search'
  resources :pictureposts do
    resources :comments, only: [:create]
  end
  post '/like/:picturepost_id', to: 'likes#like', as: 'like'
  delete '/like/:picturepost_id', to: 'likes#unlike', as: 'unlike'
  root 'home#top'
  get 'home/top'
end

app/views/partials/_error_messages.html.erb
<% if object.errors.any? %>
  <%= pluralize(object.errors.count, "erorr") %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/partials/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message%>
  </div>
<% end %>

app/views/partials/_follow-btn.html.erb
<% if current_user.following?(user)%>
  <%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
    html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-outline-secondary btn-sm" %>
  <% end %>
<% else %>
  <%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-outline-secondary btn-sm" %>
  <% end %>
<% end %>

app/views/partials/_footer.html.erb
<footer>
  <div class="row justify-content-center">
    <% if user_signed_in? %>
      <%= link_to "写真を投稿する", new_picturepost_path, class: "btn btn-outline-light" %>
    <% end %>
    <hr class="socket">
    &copy; Insta Clone
  </div>
</footer>

app/views/partials/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <%= link_to "INSTA CLONE", "/", class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">           
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "News", pictureposts_path, class: "nav-link" %>
          </li> 
          <li class="nav-item">
            <%= link_to "Mypage", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link mr-5" %>
          </li>
        <% end %>        
        <%= form_with url:'/pictureposts/search', method: :get, class: "form-inline my-2 my-lg-0", local: true do |f|%>
          <%= f.text_field :search, class:"form-control mr-sm-2" %>
          <%= f.submit 'Search', class:"btn btn-outline-secondary my-2 my-sm-0" %>
        <% end %>        
      </ul>
    </div>
  </nav>
</header>