config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  resources :users, only: :show do
    member do
      get :following
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  get '/pictureposts/search', to: 'pictureposts#search'
  resources :pictureposts do
    resources :comments, only: [:create]
  end
  post '/like/:picturepost_id', to: 'likes#like', as: 'like'
  delete '/like/:picturepost_id', to: 'likes#unlike', as: 'unlike'
  root 'home#top'
  get 'home/top'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :picturepost, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_valiables

  def like
    like = current_user.likes.new(picturepost_id: @picturepost.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(picturepost_id: @picturepost.id)
    like.destroy
  end

  private

  def set_valiables
    @picturepost = Picturepost.find(params[:picturepost_id])
    @id_name = "#like-link-#{@picturepost.id}"
  end
end

app/views/likes/_like.html.erb
<div class="like-link" id="like-link-<%= picturepost.id %>">
  <% if current_user.likes.find_by(picturepost_id: picturepost.id) %>
    <%= link_to unlike_path(picturepost.id), method: :delete, remote: true do%>
      <div class="like_button pb-2"><%= picturepost.likes.count %> likes ♥ </div>
    <% end %>
  <% else %>
    <%= link_to like_path(picturepost.id), method: :post, remote: true do %>
      <div class="like_button SPRITE_downarrow pb-2"><%= picturepost.likes.count %> likes ♡ </div>
    <% end %>
  <% end %>
</div>

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", picturepost: @picturepost )) %>');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like", picturepost: @picturepost  )) %>');